name: docs
on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
    uses: nimbase/setup-nim-action/.github/workflows/docs.yml@main
    with:
      pre-docs-command: |
        nimble install kapsis